# filter_sp500_candidates.py
import argparse
from pathlib import Path

import pandas as pd


def parse_args():
    p = argparse.ArgumentParser(
        description="Filter S&P500 stats to find good trading candidates."
    )
    p.add_argument(
        "--stats_file",
        type=str,
        default="up_move_stats_sp500_1y.csv",
        help="Input CSV file generated by up_move_stats.",
    )
    p.add_argument(
        "--max_min_invest_jpy",
        type=int,
        default=80000,
        help="Maximum 1-share minimum investment in JPY (default: 80000).",
    )
    p.add_argument(
        "--min_up1_days",
        type=int,
        default=50,
        help="Minimum number of +1%% days in the last period (default: 50).",
    )
    p.add_argument(
        "--min_days_total",
        type=int,
        default=200,
        help="Minimum number of trading days required (default: 200).",
    )
    p.add_argument(
        "--output",
        type=str,
        default="sp500_candidates.csv",
        help="Output CSV file for filtered candidates.",
    )
    return p.parse_args()


def main():
    args = parse_args()
    stats_path = Path(args.stats_file)
    if not stats_path.exists():
        raise FileNotFoundError(f"Stats file not found: {stats_path}")

    df = pd.read_csv(stats_path)

    required_cols = {
        "symbol",
        "days_total",
        "up_1pct_days",
        "up_5pct_days",
        "up_10pct_days",
        "last_price_usd",
        "min_invest_jpy",
    }
    missing = required_cols - set(df.columns)
    if missing:
        raise RuntimeError(f"Missing expected columns in stats file: {missing}")

    # フィルタ条件
    cond = (
        (df["days_total"] >= args.min_days_total)
        & (df["up_1pct_days"] >= args.min_up1_days)
        & (df["min_invest_jpy"] <= args.max_min_invest_jpy)
    )

    df_filtered = df[cond].copy()

    # シンプルな「ボラティリティスコア」: up_1pct_days の割合
    df_filtered["up1_ratio"] = df_filtered["up_1pct_days"] / df_filtered["days_total"]

    # ボラティリティスコア高い順に並べる
    df_filtered = df_filtered.sort_values("up1_ratio", ascending=False)

    out_path = Path(args.output)
    df_filtered.to_csv(out_path, index=False)

    print("==============================================")
    print("Filtered candidates summary")
    print("==============================================")
    print(
        f"Loaded {len(df)} symbols from {stats_path}, "
        f"filtered down to {len(df_filtered)} symbols."
    )
    print()
    print(
        df_filtered[
            [
                "symbol",
                "days_total",
                "up_1pct_days",
                "up_5pct_days",
                "up_10pct_days",
                "last_price_usd",
                "min_invest_jpy",
                "up1_ratio",
            ]
        ]
        .head(30)
        .to_string(index=False)
    )
    print()
    print(f"Saved filtered candidates to {out_path}")


if __name__ == "__main__":
    main()
